//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicAlert.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NicAlert.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity: .
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: .
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative DNS: .
        /// </summary>
        public static string Alternative_dns {
            get {
                return ResourceManager.GetString("Alternative_dns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City: .
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Hours: .
        /// </summary>
        public static string Contact_Hours {
            get {
                return ResourceManager.GetString("Contact_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country: .
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Server.
        /// </summary>
        public static string DnsServer {
            get {
                return ResourceManager.GetString("DnsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Information.
        /// </summary>
        public static string Domain_Information {
            get {
                return ResourceManager.GetString("Domain_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Searching.
        /// </summary>
        public static string Domain_Searching {
            get {
                return ResourceManager.GetString("Domain_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax: .
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address: .
        /// </summary>
        public static string IP_Address {
            get {
                return ResourceManager.GetString("IP_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Entity.
        /// </summary>
        public static string Managing_Entity {
            get {
                return ResourceManager.GetString("Managing_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain is available.
        /// </summary>
        public static string Message_domain_available {
            get {
                return ResourceManager.GetString("Message_domain_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information is not available in this moment. .
        /// </summary>
        public static string Message_info_not_available {
            get {
                return ResourceManager.GetString("Message_info_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text must be greater than or equal to 1 char.
        /// </summary>
        public static string Message_text_must_be_greater_than_one {
            get {
                return ResourceManager.GetString("Message_text_must_be_greater_than_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text must be less than or equal to 19 chars.
        /// </summary>
        public static string Message_text_must_be_less_than_19_chars {
            get {
                return ResourceManager.GetString("Message_text_must_be_less_than_19_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain name hasn´t recent transactions recorded.
        /// </summary>
        public static string MessageNoFoundTransaction {
            get {
                return ResourceManager.GetString("MessageNoFoundTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operador.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propietario.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person in charge.
        /// </summary>
        public static string Person_in_charge {
            get {
                return ResourceManager.GetString("Person_in_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone: .
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary DNS: .
        /// </summary>
        public static string Primary_dns {
            get {
                return ResourceManager.GetString("Primary_dns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering Entity.
        /// </summary>
        public static string Registering_Entity {
            get {
                return ResourceManager.GetString("Registering_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secundary DNS: .
        /// </summary>
        public static string Secundary_dns {
            get {
                return ResourceManager.GetString("Secundary_dns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Servers.
        /// </summary>
        public static string Servers_dns {
            get {
                return ResourceManager.GetString("Servers_dns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State: .
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Contact.
        /// </summary>
        public static string Technical_Contact {
            get {
                return ResourceManager.GetString("Technical_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction by Domain.
        /// </summary>
        public static string TransactionByDomain {
            get {
                return ResourceManager.GetString("TransactionByDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction by ID.
        /// </summary>
        public static string TransactionById {
            get {
                return ResourceManager.GetString("TransactionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of domain.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a searching type.
        /// </summary>
        public static string Type_Searching {
            get {
                return ResourceManager.GetString("Type_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unknow error..
        /// </summary>
        public static string Unknow_Error {
            get {
                return ResourceManager.GetString("Unknow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code: .
        /// </summary>
        public static string Zip_Code {
            get {
                return ResourceManager.GetString("Zip_Code", resourceCulture);
            }
        }
    }
}
